import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
// import Header from "./components/Header";

const exo = Exo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Joseph Simpson Development Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={exo.className}>
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
